<?php
  if (empty($zanrhra["id_zanru"])&&empty($zanrhra["id_hry"])) {
?>
<h1>Vložení nového spojení žánru a hry</h1>
<?php
  } else {
?> 
<h1>Editace spojení žánru a hry</h1>
<?php
  }
?>
 
 <form method="post">
   <div>
     <label for="id_zanru">id_zanru</label>
     <input type="text" name="id_zanru" id="id_zanru"
     value="<?= $zanrhra["id_zanru"] ?>" required>
   </div>
   <div>
     <label for="id_hry">id_hry</label>
     <input type="text" name="id_hry" id="id_hry"
     value="<?= $zanrhra["id_hry"] ?>" required>
   </div>
      
   <input type="submit" value="Uložit spojení">
 </form>
     
     