<div class="adminEdit">
 <?php
  if (empty($video["id_vid"])) {
?>
<h1>Vložení nového videa</h1>
<?php
  } else {
?> 

<h1>Editace videa</h1>

 <?php
  }
?>
 <form method="post" enctype="multipart/form-data">
   <input type="hidden" name="id_vid" 
     value="<?= $video["id_vid"] ?>">

   <div class="radek">
<div class="s25">
      <label for="link">Youtube link</label>
</div>
<div class="s75">
      <input type="text" name="link" id="link"
     value="<?= $video["link"] ?>" required>
   </div>
</div>
    
   <?php
  if (empty($video["id_vid"])) {
   ?>
       <div class="radek">
<div class="s25">
              <label>Hra</label>
</div>
<div class="s75" id="posunutiChosen">
             <select class="chosen-select" name="id_hry" data-placeholder="Vyber hru"> 
            <?php
               foreach($hry as $hra){
               
            ?>  
                <option value = "<?= $hra["id_hry"] ?>"><?= $hra["Jmeno"] ?></option> 
           <?php
                 }
            ?>
            </select>  
</div>
            
  
   </div>    
    <?php
  } else {
?> 
        <div class="radek">
           <div class="s25">
              <label>Hra</label>
           </div>
          <div class="s75" id="posunutiChosen">
             <select class="chosen-select" name="id_hry" data-placeholder="Vyber hru"> 
            <option value = "<?= $video["id_hry"] ?>"><?= $video["Jmeno"][0] ?></option>
            <?php
               foreach($hry as $hra){
               if($hra["Jmeno"]!==$video["Jmeno"][0]){
            ?>  
                <option value = "<?= $hra["id_hry"] ?>"><?= $hra["Jmeno"] ?></option> 
           <?php
                } }
            ?>
            </select>  
            
          </div>
  
   </div>  
      
<?php
  }
?>    
     
  <div class="radek">
    <input type="submit" value="Uložit údaje videa">
  </div>
 </form>




     
     
</div>

<?php
if (isset($_SESSION["uzivatel"])){
	

 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");
 
</script>

<?php
}  
}
?>