<div class="adminEdit">
 <?php
  if (empty($hry["id_hry"])) {
?>
<h1>Vložení nové hry</h1>
<?php
  } else {
?>
<h1>Editace hry</h1>
<?php
  }
?>

 <form method="post">
   <input type="hidden" name="id_hry"
     value="<?= $hry["id_hry"] ?>">
   <div class="radek">
    <div class="s25">
      <label for="Jmeno">Jméno</label>
    </div>
<div class="s75">
      <input type="text" name="Jmeno" id="Jmeno"
     value="<?= $hry["Jmeno"] ?>" required>
</div>
   </div>
   <div class="radek">
     <div class="s25">
      <label for="obsah">Obsah</label>
     </div>
<div class="s75">
 <textarea name="obsah" id="obsah"> <?= $hry["obsah"] ?> </textarea>

</div>
   </div>
   <div class="radek">
    <div class="s25">
      <label for="datum_vydani">Datum vydání</label>
    </div>
<div class="s75">
      <input type="date" name="datum_vydani" id="datum_vydani"
     value="<?= $hry["datum_vydani"] ?>" required>
</div>
   </div>
   <div class="radek">
    <div class="s25">
      <label for="vyvojar">Vývojář</label>
    </div>
     <div class="s75">
      <input type="text" name="vyvojar" id="vyvojar"
     value="<?= $hry["vyvojar"] ?>" required>
     </div>
   </div>

   <div class="radek">
  <div class="s25">
      <label for="platforma">Platforma</label>
  </div>

           <div class="s75" id="posunutiChosen">
              <select class="chosen-select" name="platforma" data-placeholder="Vyber platformu" required>
                <?php
                 if (empty($hry["id_hry"])) {
                ?>

               <?php
                 } else {
                ?>
                 <option value = "<?= $hry["platforma"] ?>"><?= $hry["platforma"] ?></option>
                <?php
                 }
                ?>
                  <optgroup label="PC">
                       <option value = "PC">PC</option>
                       <option value = "Notebook">Notebook</option>
                  </optgroup>
                 <optgroup label="PlayStation">
                         <option value = "Playstation Portable">Playstation Portable</option>
                         <option value = "Playstation 1">Playstation 1</option>
                         <option value = "Playstation 2">Playstation 2</option>
                         <option value = "Playstation 3">Playstation 3</option>
                         <option value = "Playstation 4">Playstation 4</option>
                         <option value = "Playstation 5">Playstation 5</option>
                  </optgroup>
                  <optgroup label="Xbox">
                         <option value = "Xbox">Xbox</option>
                         <option value = "Xbox 360">Xbox 360</option>
                         <option value = "Xbox One">Xbox One</option>
                  </optgroup>
                  <optgroup label="Mobil">
                         <option value = "Android">Android</option>
                         <option value = "iOS Apple">iOS Apple</option>
                  </optgroup>
            </select>
           </div>


   </div>

    <div class="radek">
    <div class="s25">
      <label for="zanr">Žánry</label>
    </div>
          <div class="s75">
             <select class="chosen-select" name="zanr[ ]" multiple data-placeholder="Vyber žánry">
            <?php
               foreach($zanry as $zanr){

            ?>
                <option value = "<?= $zanr["id_zanru"] ?>"><?= $zanr["nazev"] ?></option>
                <?php
                 }
                ?>
            </select>
          </div>
   </div>


  <div class="radek">
    <input type="submit" value="Uložit údaje hry">
  </div>
 </form>

</div>


<?php
if (isset($_SESSION["uzivatel"])){


 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");

</script>

<?php
}
}
?>
