<div class="adminEdit">
<?php
  if (empty($uzivatel["ID_uzivatele"])) {
?>

 

<h1>Vložení nového uživatele</h1>

 <form method="post">
<?php
  } else {
?> 

<h1>Editace uživatele</h1>

 <form method="post">
     <input type="hidden" name="uprava" 
     value=1>
<?php
  }
?>
    
   <input type="hidden" name="ID_uzivatele" 
     value="<?= $uzivatel["ID_uzivatele"] ?>">
     
     
     
   <div class="radek">
   <div class="s25">   
     <label for="prezdivka">Nickname</label>
     
   </div>
<div class="s75">
    
     <input type="text" name="prezdivka" id="prezdivka"
     value="<?= $uzivatel["prezdivka"] ?>" required>
     
</div>
</div> 
   
   
   
    <div class="radek">
    
<div class="s25">
      <label for="jmeno">Jméno</label>
</div>
     
<div class="s75">
      <input type="text" name="jmeno" id="jmeno"
      value="<?= $uzivatel["jmeno"] ?>" required>
      
</div>
   </div>
   
    <div class="radek">
    
   <div class="s25">
      <label for="prijmeni">Přijmení</label>
   </div>
     
<div class="s75">
      <input type="text" name="prijmeni" id="prijmeni"
      value="<?= $uzivatel["prijmeni"] ?>" required>
</div>
      
   </div>   
   
   <div class="radek">
   
<div class="s25">
      <label for="email">Email</label>
</div>
     
<div class="s75">
      <input type="email" name="email" id="email"
     value="<?= $uzivatel["email"] ?>" required>
</div>
     
   </div>
   
     <?php
      if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
     ?>

     
      <?php
       if(!empty($uzivatel["ID_uzivatele"])){
      ?>
  
    <div class="radek">                
    <a href="/zmenaHesla/<?= $uzivatel["ID_uzivatele"]?>" class="doplnkovyStylLinku">Změna hesla</a>
       
       <?php
       }else{
       ?>
       <div class="s75">
      <input type="password" name="heslo" id="heslo"
      value="<?= $uzivatel["heslo"] ?>">
</div>
</div> 
       
       <?php  } }else{
       ?>
       

    <div class="radek">                
    <a href="/zmenaHesla" class="doplnkovyStylLinku">Změna hesla</a>
     
       <?php
         }
       ?>

   <input type="submit" value="Uložit údaje uživatele">
        </div>
 </form>
     
</div>     

<?php
if (isset($_SESSION["uzivatel"])){
	

 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");
 
</script>

<?php
}  
}
?>