<div class="adminEdit">
 <?php
  if (empty($zanr["id_zanru"])) {
?>
<h1>Vložení nového žánru</h1>
<?php
  } else {
?> 
<h1>Editace žánru</h1>
<?php
  }
?>
 
 <form method="post">
   <input type="hidden" name="id_zanru" 
     value="<?= $zanr["id_zanru"] ?>">
   <div class="radek">
<div class="s25">
      <label for="nazev">Název</label>
</div>
<div class="s75">
      <input type="text" name="nazev" id="nazev"
     value="<?= $zanr["nazev"] ?>" required>
</div>
   </div>
   <div class="radek">
   <div class="s25">
      <label for="popis">Popis</label>
   </div>
     
   <div class="s75">
 <textarea name="popis" id="obsah"><?= $zanr["popis"] ?></textarea>
<script>
CKEDITOR.replace( 'obsah', {
} );
</script>   
</div>  
     

   </div>
      
   <div class="radek">
    <input type="submit" value="Uložit údaje žánru">
   </div>
 </form>
     
     
</div>


<?php
if (isset($_SESSION["uzivatel"])){
	

 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");
 
</script>

<?php
}  
}
?>