<?php
  if (empty($hry["id_hry"])) {
?>
<h1>Vložení nové hry</h1>
<?php
  } else {
?> 
<h1>Editace hry</h1>
<?php
  }
?>
 
 <form method="post">
   <input type="hidden" name="id_hry" 
     value="<?= $hry["id_hry"] ?>">
   <div>
     <label for="Jmeno">Jméno</label>
     <input type="text" name="Jmeno" id="Jmeno"
     value="<?= $hry["Jmeno"] ?>" required>
   </div>
   <div>
     <label for="obsah">Obsah</label>
     <input type="text" name="obsah" id="obsah"
     value="<?= $hry["obsah"] ?>" required>
   </div>
   <div>
     <label for="datum_vydani">Datum vydání</label>
     <input type="date" name="datum_vydani" id="datum_vydani"
     value="<?= $hry["datum_vydani"] ?>" required>
   </div>
   <div>
     <label for="vyvojar">Vývojář</label>
     <input type="text" name="vyvojar" id="vyvojar"
     value="<?= $hry["vyvojar"] ?>" required>
   </div>
   
   <div>
     <label for="platforma">Platforma</label>
     
             <select class="chosen-select" name="platforma" data-placeholder="Vyber platformu" required> 
                <?php
                 if (empty($hry["id_hry"])) {
                ?>
                 
               <?php
                 } else {
                ?>  
                 <option value = "<?= $hry["platforma"] ?>"><?= $hry["platforma"] ?></option>
                <?php
                 }
                ?>               
                  <optgroup label="PC">
                       <option value = "PC">PC</option>
                       <option value = "Notebook">Notebook</option>
                  </optgroup>
                 <optgroup label="PlayStation">
                         <option value = "Playstation Portable">Playstation Portable</option>
                         <option value = "Playstation 1">Playstation 1</option>
                         <option value = "Playstation 2">Playstation 2</option>
                         <option value = "Playstation 3">Playstation 3</option>
                         <option value = "Playstation 4">Playstation 4</option>
                         <option value = "Playstation 5">Playstation 5</option>
                  </optgroup>
                  <optgroup label="Xbox">
                         <option value = "Xbox">Xbox</option>
                         <option value = "Xbox 360">Xbox 360</option>
                         <option value = "Xbox One">Xbox One</option>
                         <option value = "Xbox One S">Xbox One S</option>
                         <option value = "Xbox One X">Xbox One X</option>
                  </optgroup>
                  <optgroup label="Mobil">
                         <option value = "Android">Android</option>
                         <option value = "iOS Apple">iOS Apple</option>
                  </optgroup>                  
            </select>  
     
     
   </div>
  
    <div>  <label for="zanr">Žánry</label>  
            <select class="chosen-select" name="zanr[ ]" multiple data-placeholder="Vyber žánry"> 
            <?php
               foreach($zanry as $zanr){
               
            ?>  
                <option value = "<?= $zanr["id_zanru"] ?>"><?= $zanr["nazev"] ?></option> 
                <?php
                 }
                ?>
            </select>   
   </div>                             
  
      
   <input type="submit" value="Uložit údaje hry">
 </form>
       