<div class="adminEdit">

<h1>Přiřaď jména obrázkům</h1>

?>

 <form method="post">
  
   <?php
    
   ?>
 
  <input type="text" name="nazev_obr" id="nazev_obr" value="<?= $obrazek["nazev_obr"] ?>">
 
 
  
   <?php
    
   ?>
  
  
 </form>

</div>


<?php
if (isset($_SESSION["uzivatel"])){


 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");

</script>

<?php
}
}
?>
