<?php
  if (empty($uzivatel["id_uzivatele"])) {
?>
<h1>Vložení nového uživatele</h1>

 <form method="post">
<?php
  } else {
?> 
<h1>Editace uživatele</h1>

 <form method="post">
     <input type="hidden" name="uprava" 
     value=1>
<?php
  }
?>
    
   <input type="hidden" name="ID_uzivatele" 
     value="<?= $uzivatel["ID_uzivatele"] ?>">
   <div>
     <label for="prezdivka">Nickname</label>
     <input type="text" name="prezdivka" id="prezdivka"
     value="<?= $uzivatel["prezdivka"] ?>" required>
   </div> 
   
    <div>
     <label for="jmeno">Jméno</label>
     <input type="text" name="jmeno" id="jmeno"
      value="<?= $uzivatel["jmeno"] ?>" required>
   </div>
   
    <div>
     <label for="prijmeni">Přijmení</label>
     <input type="text" name="prijmeni" id="prijmeni"
      value="<?= $uzivatel["prijmeni"] ?>" required>
   </div>   
   
   <div>
     <label for="email">Email</label>
     <input type="email" name="email" id="email"
     value="<?= $uzivatel["email"] ?>" required>
   </div>
   
   <div>
     <label for="heslo">Heslo</label>
     <input type="password" name="heslo" id="heslo"
      value="<?= $uzivatel["heslo"] ?>" required>
     </div>
   
                    
   
   <input type="submit" value="Uložit údaje uživatele">
 </form>
     
     