<?php
  if (empty($obrazek["id_obr"])) {
?>
<h1>Vložení nového obrázku</h1>
<?php
  } else {
?> 

<h1>Editace obrázku</h1>

 <?php
  }
?>
 <form method="post" enctype="multipart/form-data">
   <input type="hidden" name="id_obr" 
     value="<?= $obrazek["id_obr"] ?>">
     
    <input type="file" name="obrazek">

   <div>
     <label for="nazev_obr">Název</label>
     <input type="text" name="nazev_obr" id="nazev_obr"
     value="<?= $obrazek["nazev_obr"] ?>" required>
   </div>
    
   <?php
  if (empty($obrazek["id_obr"])) {
   ?>
       <div>
             <label for="hra">Hra</label>
            <select class="chosen-select" name="id_hry" data-placeholder="Vyber hru"> 
            <?php
               foreach($hry as $hra){
               
            ?>  
                <option value = "<?= $hra["id_hry"] ?>"><?= $hra["Jmeno"] ?></option> 
           <?php
                 }
            ?>
            </select>  
            
  
   </div>    
    <?php
  } else {
?> 
        <div>
             <label for="hra">Hra</label>
            <select class="chosen-select" name="id_hry" data-placeholder="Vyber hru"> 
            <option value = "<?= $obrazek["id_hry"] ?>"><?= $obrazek["Jmeno"][0] ?></option>
            <?php
               foreach($hry as $hra){
               if($hra["Jmeno"]!==$obrazek["Jmeno"][0]){
            ?>  
                <option value = "<?= $hra["id_hry"] ?>"><?= $hra["Jmeno"] ?></option> 
           <?php
                } }
            ?>
            </select>  
            
  
   </div>  
      
<?php
  }
?>    
     
   <input type="submit" value="Uložit údaje obrázku">
 </form>




     
     