<?php
  if (empty($hodnoceni["id_hod"])) {
?>
<h1>Vložení nového hodnocení</h1>
<?php
  } else {
?> 
<h1>Editace hodnocení</h1>
<?php
  }
?>
 
 <form method="post">
   <input type="hidden" name="id_hod" 
     value="<?= $hodnoceni["id_hod"] ?>">
   <div>
     <label for="hodnoceni">%</label>
     <input type="text" name="hodnoceni" id="hodnoceni"
     value="<?= $hodnoceni["hodnoceni"] ?>" required>
   </div>
   <div>
     <label for="komentar">Recenze</label>
     <input type="text" name="komentar" id="komentar"
     value="<?= $hodnoceni["komentar"] ?>" required>
   </div>
   <div>
     <label for="id_uzivatele">Uzivatel</label>
     <input type="text" name="id_uzivatele" id="id_uzivatele"
     value="<?= $hodnoceni["id_uzivatele"] ?>" required>
   </div>
   
      <?php
  if (empty($obrazek["id_obr"])) {
   ?>
       <div>
             <label for="hra">Hra</label>
            <select class="chosen-select" name="id_hry" data-placeholder="Vyber hru"> 
            <?php
               foreach($hry as $hra){
               
            ?>  
                <option value = "<?= $hra["id_hry"] ?>"><?= $hra["Jmeno"] ?></option> 
           <?php
                 }
            ?>
            </select>  
            
  
   </div>    
    <?php
  } else  {
?> 
        <div>
             <label for="hra">Hra</label>
            <select class="chosen-select" name="id_hry" data-placeholder="Vyber hru"> 
            <option value = "<?= $hodnoceni["id_hry"] ?>"><?= $hodnoceni["Jmeno"][0] ?></option>
            <?php
               foreach($hry as $hra){
               if($hra["Jmeno"]!==$hodnoceni["Jmeno"][0]){
            ?>  
                <option value = "<?= $hra["id_hry"] ?>"><?= $hra["Jmeno"] ?></option> 
           <?php
                } }
            ?>
            </select>  
            
  
   </div>  
      
<?php
  }
?> 
   
   
   <input type="submit" value="Uložit údaje hodnocení">
 </form>
     
     