<div class="admin">

 <h1>Hodnocení</h1>
    

 
     <table>
     <tr>
       <th>%</th>
       <th>Recenze</th>
       <th>Uzivatel</th>
       <th>Hra</th>  
       <th>Administrace</th>
     </tr>
     <?php foreach ($hodnoceni as $hodnot) { ?>
        <tr>
          <td><?= $hodnot["hodnoceni"] ?></td>
          <td><?= $hodnot["komentar"] ?></td>
          <td><?= $hodnot["id_uzivatele"] ?></td>
          <td><?= $hodnot["id_hry"] ?></td>
          
          <td>
            <a href="editace-hodnoceni/<?= $hodnot["id_hod"] ?>">Upravit</a>
            <a href="hodnoceni/<?= $hodnot["id_hod"] ?>/odstranit">Odstranit</a>
           </td> 
        </tr>   	
     <?php } ?>
     </table>     
     <p>
    <a href="editace-hodnoceni">Nové hodnocení</a>
  </p>  
      </div>
      

      
<?php
if (isset($_SESSION["uzivatel"])){
	

 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");
 
</script>

<?php
}  
}
?>