<div class="admin">

 <h1>Hodnocení</h1>
    

 
     <table id="datatable">
     <thead>
     <tr class = "hlavicky">
       <th>%</th>
       <th id="upravitelne">Recenze</th>
       <th>Uzivatel</th>
       <th>Hra</th>  
       <th>Administrace</th>
     </tr>  
      </thead>
      <tbody>
     <?php foreach ($hodnoceni as $hodnot) { ?>                                 
        <tr>
          <td><div class="bunka_tabulky"><?= $hodnot["hodnoceni"]?></div></td>
          <td id="upravitelne"><div class="bunka_tabulky"><?= $hodnot["komentar"]?></div></td>
          <td><div class="bunka_tabulky"><?= $hodnot["prezdivka"]?></div></td>
          <td><div class="bunka_tabulky"><?= $hodnot["Jmeno"]?></div></td>
          
          <td><div class="bunka_tabulky" id="administrace">
            <a href="editace-hodnoceni/<?= $hodnot["id_hod"] ?>">Upravit</a>
            <a href="hodnoceni/<?= $hodnot["id_hod"] ?>/odstranit">Odstranit</a>
           </div></td> 
        </tr>  
        </tbody> 	
     <?php } ?>
     </table>     
     <p>
    <a href="editace-hodnoceni">Nové hodnocení</a>
  </p>  
      </div>
      

      
<?php
if (isset($_SESSION["uzivatel"])){
	

 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");
 
</script>

<?php
}  
}
?>