<div class="admin">

 <h1>Hry</h1>
    

 
     <table id="datatable">
     <thead>
     <tr class = "hlavicky">
       <th>Název</th>
       <th class="upravitelne">Datum vydání</th>
       <th class="upravitelne">Vývojář</th>
       <th class="upravitelne">Platforma</th>
       <th class="upravitelne1">Žánry</th>
       <th>Administrace</th>
     </tr>
     </thead>
     <tbody>
     <?php foreach ($hry as $hra) { ?>
        <tr>
          <td><div class="bunka_tabulky"><?= $hra["Jmeno"] ?></div></td>
          <td class="upravitelne"><div class="bunka_tabulky" ><?=  $hra["datum_vydani"] ?></div></td>
          <td class="upravitelne"><div class="bunka_tabulky" ><?= $hra["vyvojar"] ?></div></td>
          <td class="upravitelne"><div class="bunka_tabulky" ><?= $hra["platforma"] ?></div></td>
         <td class="upravitelne1"><div class="bunka_tabulky">
           <?php foreach ($hryy as $zanryProHru) {
            if($hra["id_hry"]==$zanryProHru["id_hry"]){
     ?>          
            
              
            <?= $zanryProHru["nazev"] ?>,
            
       <?php
       
        }
        } ?>
               
         </div></td>
          <td><div class="bunka_tabulky administrace">
            <a href="editace-hry/<?= $hra["id_hry"] ?>">Upravit</a>
            <a href="hry/<?= $hra["id_hry"] ?>/odstranit">Odstranit</a>
           </div></td> 
        </tr>   	
     <?php } ?> 
     </tbody>
     </table>   
     
  <p>
    <a href="editace-hry">Nová hra</a>
  </p>   
</div>


<?php
if (isset($_SESSION["uzivatel"])){
	

 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");
 
</script>

<?php
}  
}
?>