<div class="hraNahled">

 <div class="hraInfo">
  <div class="NazevHry">   
 
       <div class="jmeno">
       
   <h1><?= $hra["Jmeno"] ?></h1>         
   
     </div>


 

      <div class="hodnoceniHry">
       
           <?php
            if(!empty($hra["celkoveHodnoceni"])){
           ?>
         <h2><?= $hra["celkoveHodnoceni"] ?>%</h2>  
           <?php
            }else{
           ?>
           <h2>-%</h2>
           <?php
            }
           ?>
        </div> 
  </div>
  
          <div class="zanry">
         
     
         <?php
          foreach ($zanry as $zanrprohru) {
            	 
         ?>
         
          <strong>  <?= $zanrprohru["Zanr"]["nazev"] ?>  </strong>
         <?php
           }
         ?>
           </div> 
           
           
    <div class="shrnuti">
          <?= $hra["obsah"] ?>
        </div>
        
        
         <div class="obsah">
   
          
      <table>
       
       <tr>
       <th>Vývojář: </th>
       <th><?= $hra["vyvojar"] ?>  </th>
       </tr>
       <tr>
       <th>Datum vydání: </th>
       <th> <?= date_format(date_create($hra["datum_vydani"]), 'j. n. Y') ?></th>
       </tr>
       <tr>
       <th>Platforma: </th>
       <th><?= $hra["platforma"]?></th>
       </tr>       
       </table>
       
   </div>

   
   </div>

   
   
   
   
   
 
   <div class="galerie">
   <h2>
    Galerie
   </h2>
    <div class="obrazky">
     
   
     <?php
    
    foreach ($obrazky as $obr) {
    if ($obr["id_hry"]==$hra["id_hry"]) {
    ?>  
   <div class="obrazek">

   <div>
     
         
    
    <a data-fancybox="gallery" href="<?=$obr["download"]?>"><img src="<?=$obr["nahled"]?>" height="150" width="150" alt=""></a>
     </div> 

  </div>
    <?php
    }
    } 
    ?>  
   
    </div>
    
    </div> 
    
    
    <div class="galerieVidei">
     <h2>
      Videa
     </h2>
   
     <?php
     foreach ($video as $vid) {
      if ($hra["id_hry"]==$vid["id_hry"]) {	
     
     ?>
    <iframe class="video" allowfullscreen
     src="<?= $vid["link"] ?>">
    </iframe> 
      <?php
      
       }
       } 
      ?>
      </div> 
    
      
 

<div class="komentare">
  <h2>
   Hodnocení
  </h2>
  <?php
   if($overeni["uzivatel"] == 1){
      if ($overeni["hodnoceni"]==0) {
      	
      
  ?>
  <a href="/editaceHodnoceniU/<?= $hra["id_hry"] ?>" class="pridejKom">Přidej hodnocení</a>
  
  <?php
  }else{
  
  ?>
  
  
   <a href="/editaceHodnoceniU/<?= $hra["id_hry"] ?>" class="pridejKom">Uprav své hodnocení</a>
  
  <?php 
  
  }
  
  }
  
  foreach ($hodnoceni as $hod) {
     ?>
 

                <div class="komentarovy_box">
                  <div class="inside_comment">
                    <div class="kometar_hlavicka">
                      <div class="komentarPrezdivka"><strong><?= $hod["prezdivka"] ?></strong></div>
                      <div class="komentarHodnoceni"><strong><?= $hod["hodnoceni"] ?>%</strong></div>
                    </div>
                  </div>
                  <div class="teloKomentare">
                    <p><?= $hod["komentar"] ?></p>
                  </div>
                </div>
  <?php
     }
  ?>
 
</div>
</div>



<?php
if (isset($_SESSION["uzivatel"])){
 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/hra.jpg)");
 
</script>

<?php
}
else{
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/hra.jpg)");
 
</script>

<?php
	
}  
}
?>