<div class="admin">

 <h1>Obrázky</h1>
    

     <table class="datatableObrazek">
     <thead>
     <tr class = "hlavicky">
       <th>Náhled</th>
       <th class="upravitelne">ID obrázku</th>
       <th class="upravitelne">Typ</th>
       <th>Hra</th> 
       <th>Administrace</th>
     </tr>
     </thead>
     <tbody>
     <?php 
     
     foreach ($obrazek as $obr) { 
   
    ?>
    <tr>
          <td><a data-fancybox="gallery" class="nahledEdit" href="<?=$obr["download"]?>"><img src="<?=$obr["nahled"]?>" height="100" width="100" alt=""></a></td>
          <td class="upravitelne"><?= $obr["id_obr"] ?></td>
          <td class="upravitelne"><?= $obr["typ"] ?></td>
          <td><div class="bunka_tabulky"><?= $obr["Jmeno"]?></div></td>
          
           <td><div class="bunka_tabulky administrace">                                                                                                                                   
            <a href="obrazek/<?= $obr["id_obr"] ?>/odstranit">Odstranit</a>
            <a href="<?=$obr["download"]?>" download>Stáhnout</a>
            </div>
           </td> 
        </tr>   	
     <?php } ?>
     </tbody>
     </table>   
     
  <p>
    <a href="editace-obrazku">Nový obrázek</a>
  </p>
  
  </div>
 
 
<?php
if (isset($_SESSION["uzivatel"])){
	

 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");
 
</script>

<?php
}  
}
?>