<div class="prihlaseni">
 <h1>Přihlášení</h1>
 
 <form method="post">
   <div class="textbox">
     <input type="text" name="prezdivka" id="prezdivka" placeholder="Přezdívka" required>
   </div>
   <div class="textbox">
     <input type="password" name="heslo" id="heslo" placeholder="Heslo" required>
   </div >
   <input type="submit" class="prihlaseniTlacitko" value="Přihlásit se">
 </form>
 
 <a href="/registraceUzivatele">Registrace</a>
     
     
</div>