<h1>Registrace uživatele</h1>
 
 <form method="post">
 
    <input type="hidden" name="ID_uzivatele">
 
    <div>
     <label for="jmeno">Jméno</label>
     <input type="text" name="jmeno" id="jmeno" required>
   </div>
   
   <div>
     <label for="prijmeni">Příjmení</label>
     <input type="text" name="prijmeni" id="prijmeni" required>
   </div>
 
   <div>
     <label for="prezdivka">Login</label>
     <input type="text" name="prezdivka" id="prezdivka" required>
   </div>
   
      <div>
     <label for="email">Email</label>
     <input type="email" name="email" id="email" required>
   </div>
   
   <div>
     <label for="heslo">Heslo</label>
     <input type="password" name="heslo" id="heslo" required>
   </div>

   <input type="submit" value="Registrovat se">
 </form>
