<div class="registrace">
 <h1>Registrace</h1>
 
 <form method="post">
 
    <input type="hidden" name="ID_uzivatele">
 
    <div class="textbox">
     <input type="text" name="jmeno" id="jmeno" placeholder="Jméno" required>
   </div>
   
   <div class="textbox">
     <input type="text" name="prijmeni" id="prijmeni" placeholder="Příjmení" required>
   </div>
 
   <div class="textbox">
     <input type="text" name="prezdivka" id="prezdivka" placeholder="Přezdívka" required>
   </div>
   
      <div class="textbox">
     <input type="email" name="email" id="email" placeholder="Email" required>
   </div>
   
   <div class="textbox">
     <input type="password" name="heslo" id="heslo" placeholder="Heslo" required>
   </div>

   <input type="submit" class="registraceTlacitko" value="Registrovat se">
 </form> 
 
  <a href="/prihlaseniUzivatele">Přihlášení</a>
     
</div>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/Registrace.jpg)");
 rootElement.style.setProperty('--barvaTextu',"black");
</script>
