<!DOCTYPE html>
<html lang='cs'>
  <head>
    <title>GameWiki</title>
    <meta charset='utf-8'>
    <base href="/">
  </head>
  <body>
  
   <nav>
  <div class="blokPrihlaseni">
  <?php
    if (!empty($prihlasenyUzivatel)) {
  ?>
     <span>Jste přihlášeni jako 
        <?= $prihlasenyUzivatel["jmeno"] ?>
        <?= $prihlasenyUzivatel["prezdivka"] ?>
        <?= $prihlasenyUzivatel["prijmeni"] ?>
        
        | <a href="#">Odhlásit se</a>
     </span>
  <?php
    } else {
  ?>
       <a href="prihlaseni-uzivatele">Přihlásit se</a>
  <?php
    }
  ?>
  </div>
     <ul>
       <li><a href="uvod">Úvod</a></li>
       <li><a href="hry">Hry</a></li>
       <li><a href="uzivatele">Uživatelé</a></li>
       <li><a href="zanr">Zanry</a></li>
       <li><a href="hodnoceni">Hodnocení</a></li>
       <li><a href="uzivatele">Uživatelé</a></li>
       <li><a href="zanrHra">SpojeniZanruHry</a></li>
     </ul>
     </nav>
     
     <section>
     <?php
       $this->kontroler->vypisPohled();
     ?>
     </section>
     
      <footer>
      
      </footer>  
  </body>
</html>