<!DOCTYPE html>
<html lang='cs'>
  <head>
    <title>GameWiki</title>   
    <meta charset='utf-8'>
    <link rel="stylesheet" href="../styly/NavCSS.css">
   
    <link rel="stylesheet" href="../styly/chosen/chosen.css" type="text/css">
        
    <link rel="stylesheet" href="../styly/chosen/chosen.min.css" type="text/css"> 
    
    <script src="../styly/chosen/docsupport/jquery-3.2.1.min.js"></script>          
    <script src="../styly/chosen/chosen.jquery.min.js"></script>
                
          <script>
           $(document).ready(function(){ 
             $(".chosen-select").chosen({
            disable_search_threshold: 0,
              width: "25%",
              no_results_text: "Nenašel jsem: "
             });
           
            
           });

          </script>
       
     
  </head>
  <body>
  <header>
  <a href="/uvod"><img src="/Obrazky/GameWiki.png" alt="GameWiki.png, 7,6kB" title="GameWiki"></a>
   <nav>
  <div class="blokPrihlaseni">
  <?php
    if (!empty($prihlasenyUzivatel)) {
  ?>
     <span>Jste přihlášeni jako 
        <?= $prihlasenyUzivatel["jmeno"] ?>
        "<?= $prihlasenyUzivatel["prezdivka"] ?>"
        <?= $prihlasenyUzivatel["prijmeni"] ?>
        
        | <a href="/prihlaseni-uzivatele/odhlasit">Odhlásit se</a>
     </span>
  <?php
    } else {
  ?>
       <a href="/prihlaseni-uzivatele">Přihlásit se</a>
  <?php
    }
  ?>
  </div>
     <ul>
       <li><a href="/uvod">Úvod</a></li>
       <li><a href="/hry">Hry</a></li>
       <li><a href="/uzivatele">Uživatelé</a></li>
       <li><a href="/zanr">Zanry</a></li>
       <li><a href="/hodnoceni">Hodnocení</a></li>
       <li><a href="/obrazek">Obrázek</a></li>
     </ul>
     </nav>

      
     
  </header>  
     <section>
     <?php
       $this->kontroler->vypisPohled();
     ?>
     </section>
     
      <footer>
     <script type="text/javascript" >
     
            $(document).ready(function(){
         $(".selectZanru").chosen();
     });
     
     </script>
  

      </footer>  
  </body> 

     
</html>