<!DOCTYPE html>
<html lang='cs'>
  <head>
    <title>GameWiki</title>   
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link rel="stylesheet" href="../styly/chosen/chosen.css" type="text/css">
        
    <link rel="stylesheet" href="../styly/chosen/chosen.min.css" type="text/css"> 
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:500|Roboto:500&display=swap&subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="../styly/styl.css">
    <script src="../styly/chosen/docsupport/jquery-3.2.1.min.js"></script>          
    <script src="../styly/chosen/chosen.jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css"></script>
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css">
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
     
                

         <script>
         $(document).ready(function(){
    var max_fields = 10;
    var wrapper = $(".container1");
    var add_button = $(".add_form_field");

    var x = 1;
    $(add_button).click(function(e) {
        e.preventDefault();
        if (x < max_fields) {
            
            x++;
            $(wrapper).append('<div class="radek"><div><div class="s25"> <label for="Videa">Video #'+x+'</label></div>'+'<div class="s75"><input type="text" name="link[] "></div></div></div></div>');
        } else {
            alert('Lze vložit maximálně 10 videí')
        }
    });

    $(wrapper).on("click", ".delete", function(e) {
    if(x>1){
        e.preventDefault();
        $('.radek').children().last().remove();
        x--;
    }
    else 
    return false;
    })
});
</script>
         


          <script>
           $(document).ready(function(){ 
             $(".chosen-select").chosen({
              disable_search_threshold: 0,
              no_results_text: "Nenašel jsem: ",
              width: "95%"
             }),
             $(".datatableObrazek").DataTable({
             "pageLength": 3,
             "lengthChange": false,
             "bInfo" : false,
                            "language": {
                "search": "Vyhledávání:",
                "zeroRecords":    "Žádné výsledky",
                "paginate": {
                      "first":      "První",
                      "last":       "Poslední",
                      "next":       "Další",
                      "previous":   "Předchozí"
                            }
                         }
    
       
             
             }
             ),
           
             $("#datatable").DataTable({
             "lengthChange": false,
             "pageLength": 6,
             "bInfo" : false,
                "language": {
                "search": "Vyhledávání:",
                "zeroRecords":    "Žádné výsledky",
                "paginate": {
                      "first":      "První",
                      "last":       "Poslední",
                      "next":       "Další",
                      "previous":   "Předchozí"
    }
  }
             
             })
           });
           
                  
           
           </script>

   

                                      
  </head>
  <body>
  <header>
   <div class="header">
     <div class="logo">
       <a href="/uvod"><img src="/Obrazky/GameWiki.png" alt="GameWiki.png, 7,6kB" title="GameWiki"></a> 
       
     </div>
     
     
  <div class="nav">
      
      
  <input type="checkbox" id="check">
  <label for="check" class="rozbal-btn">
   <i class="fas fa-bars"></i>
  </label>
   
        <div class="search_box">
    <form action="/Hledej" method="post">
      <input class="input_box" type="text" placeholder="Hledej..." name="vyhledavani">
      <button type="submit" class="search_btn"><i class="fas fa-search"></i></button>
    </form>
      </div>
     
  <ul class="menu">
                
    <li class="search_box_sbalen">
<form action="/Hledej" method="post">
      <input class="input_box_sbalen" type="text" placeholder="Hledej..." name="vyhledavani">
      <button type="submit" class="search_btn_sbalen"><i class="fas fa-search"></i></button>
</form>


      </li>
            <?php
      if (!empty($prihlasenyUzivatel)){
     if ($prihlasenyUzivatel["typ_uctu"]=="0") {
     	
      
     ?>
      <li class="overSvujMail">
         Prosím ověř svůj email!
      </li>
     <?php
     }} 
     ?> 
    <li class="prihlaseni-nav">
      
  
        <?php
    if (!empty($prihlasenyUzivatel)) {
  ?>
     <span>
      |  <?= $prihlasenyUzivatel["jmeno"] ?>
        "<?= $prihlasenyUzivatel["prezdivka"] ?>"
        <?= $prihlasenyUzivatel["prijmeni"] ?>
        
        | <a href="/prihlaseni-uzivatele/odhlasit">Odhlásit se</a>
     </span>
     
     
     
  <?php
    } else {
  ?>
       <a href="/prihlaseni-uzivatele">Přihlásit se</a>
  <?php
    }
  ?>      
  
     </li>
     
      <li class="uzivatel" >
        <a id="rozsir" href="/vypis-her">Hry</a>
      </li>  
     
     <?php
      if (!empty($prihlasenyUzivatel)){
     if ($prihlasenyUzivatel["typ_uctu"]=="1"||$prihlasenyUzivatel["typ_uctu"]=="A") {
     	
      
     ?>
     <li class="uzivatel">
      <a href="/editace-uzivatele/<?= $prihlasenyUzivatel["ID_uzivatele"] ?>">Nastavení</a>
     </li>   
     <?php
     }}
      ?>
      

      

      
     
     <?php
      if (!empty($prihlasenyUzivatel)) {
      	   if ($prihlasenyUzivatel["typ_uctu"]=="A") {
     ?>
     
     
     
          <li class="dropdown">

          
          <button class="dropbtn">Admin 
          <i class="fa fa-caret-down"></i>
        </button> 
         <div class="dropdown-content">
         <a href="/hry">Hry</a>
         <a href="/uzivatele">Uživatelé</a>
         <a href="/zanr">Žánry</a>
         <a href="/hodnoceni">Hodnocení</a>
         <a href="/obrazek">Obrázek</a>
         <a href="/video">Video</a>
        </div>
       </li>

     <?php
        }
      }
     ?>    
        
     
  <label for="check" class="schovej-btn">
   <i class="fas fa-times"></i>
  </label>  
  

  </ul>  

 </div>    
    
                                                                                                                       


  </div>
     
        
  </header>  
  
    
     <?php
       $this->kontroler->vypisPohled();
     ?>
    
     
     
       <footer>
  

      </footer>  
  </body> 

     
</html>