<div class = "banner">

<h1>GameWiki</h1>
<p>Vítejte na GameWiki</p>







</div>



<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvod.jpg)");

</script>



<?php
if (isset($_SESSION["uzivatel"])){


 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");

</script>

<?php
}
}
?>
