<div class="admin">


 <h1>Uživatelé</h1>
    

     <table id="datatable">
     <thead>
     <tr class="hlavicky">
       <th id="upravitelne">Jméno</th>
       <th id="upravitelne">Příjmení</th>
       <th>Přezdívka</th>
       <th>Email</th>
       <th>Právo</th>                             
       <th>Administrace</th>
     </tr> 
     </thead> <tbody>
     <?php foreach ($uzivatel as $uzivatel1) { ?>
        <tr>
          <td id="upravitelne"><div class="bunka_tabulky"><?= $uzivatel1["jmeno"] ?></div></td>
          <td id="upravitelne"><div class="bunka_tabulky"><?= $uzivatel1["prijmeni"] ?></div></td>
          <td><div class="bunka_tabulky"><?= $uzivatel1["prezdivka"] ?></div></td>
          <td id="upravitelne"><div class="bunka_tabulky"><?= $uzivatel1["email"] ?></div></td>
          <td><div class="bunka_tabulky"><?= $uzivatel1["typ_uctu"] ?></div></td>
          <td><div class="bunka_tabulky" id="administrace">
            <a href="editace-uzivatele/<?= $uzivatel1["ID_uzivatele"] ?>">Upravit</a>
            <a href="uzivatele/<?= $uzivatel1["ID_uzivatele"] ?>/odstranit">Odstranit</a>
           </div></td> 
        </tr>   	
     <?php } ?> 
     </tbody>
     </table>
    <p>
    <a href="editace-uzivatele">Nový uživatel</a>
  </p>
    
     </div>
     

<?php
if (isset($_SESSION["uzivatel"])){
	

 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");
 
</script>

<?php
}  
}
?>