<div class="admin">


 <h1>Uživatelé</h1>
    

     <table>
     <tr>
       <th>Jméno</th>
       <th>Příjmení</th>
       <th>Přezdívka</th>
       <th>Email</th>
       <th>Ověřovací kód</th>
       <th>Právo</th>
       <th>Administrace</th>
     </tr>
     <?php foreach ($uzivatel as $uzivatel1) { ?>
        <tr>
          <td><?= $uzivatel1["jmeno"] ?></td>
          <td><?= $uzivatel1["prijmeni"] ?></td>
          <td><?= $uzivatel1["prezdivka"] ?></td>
          <td><?= $uzivatel1["email"] ?></td>
          <td><?= $uzivatel1["over_kod"] ?></td>
          <td><?= $uzivatel1["typ_uctu"] ?></td>
          <td>
            <a href="editace-uzivatele/<?= $uzivatel1["ID_uzivatele"] ?>">Upravit</a>
            <a href="uzivatele/<?= $uzivatel1["ID_uzivatele"] ?>/odstranit">Odstranit</a>
           </td> 
        </tr>   	
     <?php } ?>
     </table>
    <p>
    <a href="editace-uzivatele">Nový uživatel</a>
  </p>
    
     </div>