<div class="vyhledavaniStr">
  <h1>Vyhledavání</h1>
  
  
         <div class="sortVyhledavani">
          
               <form method="post">
               <select class="chosen-select" name="zanr[ ]" multiple data-placeholder="Vyber žánry">
            <?php
               foreach($vsechnyZanry as $zanr){

            ?>
                <option value = "<?= $zanr["id_zanru"] ?>"><?= $zanr["nazev"] ?></option>
                <?php
                 }
                ?>
            </select>
             <input type="submit" value="Najdi">   
           
           </form>  
  
       
         </div>
   <table>
      <tr>
       <th>Jméno</th>
       <th>Vývojář</th>
       <th>Žánry</th>
     </tr>
     <?php
       
      foreach ($_SESSION["vysledkyVyhledavani"] as $vysledek) { 
       if (in_array($vysledek["id_hry"],$finalHry)) {
      ?>
        <tr>
          <td><a href="nahledHry/<?= $vysledek["id_hry"] ?>"><?= $vysledek["Jmeno"] ?></a></td>
          <td><?= $vysledek["vyvojar"] ?></td>
          <td>
      <?php foreach ($zanry as $zanryProHru) {
            if($vysledek["id_hry"]==$zanryProHru["id_hry"]){
     ?>                
            <?= $zanryProHru["nazev"]." " ?>         
       <?php    
        }
    }
        
}
}?> 
        </td>	  
     </tr> 
    
 </table>

        
        
</div>
 
<?php
if (isset($_SESSION["uzivatel"])){
	

 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");
 
</script>

<?php
 }  
}
?>