<div class="admin">

 <h1>Žánry</h1>

 
     <table id="datatable">
     <thead>
     <tr class="hlavicky">
       <th>Název</th> 
       <th>Popis</th>
       <th></th> 
      </tr>  
     </thead>
     <tbody>
     <?php foreach ($zanr as $zanr1) { ?>
        <tr>
          <td><?= $zanr1["nazev"] ?></td>
          <td><?= $zanr1["popis"] ?></td>
          <td>
            <a href="editace-zanru/<?= $zanr1["id_zanru"] ?>">Upravit</a>
            <a href="zanr/<?= $zanr1["id_zanru"] ?>/odstranit">Odstranit</a>
           </td> 
        </tr>   	
     <?php } ?>  
     </tbody>
     </table>
         
  <p>
    <a href="editace-zanru">Nový žánr</a>
  </p>
     </div>
     

<?php
if (isset($_SESSION["uzivatel"])){
	

 if($_SESSION["uzivatel"]["typ_uctu"]=="A"){
?>

<script>

 let rootElement = document.documentElement;
 rootElement.style.setProperty('--pozadi',"url(../Obrazky/uvodAdmin.jpg)");
 
</script>

<?php
}  
}
?>